package com.utils;
import java.math.BigDecimal;
import java.util.Date;

public class Admin {
    public static void main(String[] args) {
        LoanSnapshot loanSnapshot = new LoanSnapshot();
        loanSnapshot.setSnapshotId(0L);
        loanSnapshot.setTradeOrderNo("");
        loanSnapshot.setValid((byte)0);
        loanSnapshot.setBizDate(0);
        loanSnapshot.setEventType("");
        loanSnapshot.setBak("");
        loanSnapshot.setId(0L);
        loanSnapshot.setAccountId(0L);
        loanSnapshot.setLoanOrderNo("");
        loanSnapshot.setStatus("");
        loanSnapshot.setBankCode("");
        loanSnapshot.setBankName("");
        loanSnapshot.setBankAccountName("");
        loanSnapshot.setBankAccountNo("");
        loanSnapshot.setBankAccountType("");
        loanSnapshot.setAppliedAmount(new BigDecimal("0"));
        loanSnapshot.setDesiredAmount(new BigDecimal("0"));
        loanSnapshot.setProcessingFee(new BigDecimal("0"));
        loanSnapshot.setOriginalFee(new BigDecimal("0"));
        loanSnapshot.setPremiumFee(new BigDecimal("0"));
        loanSnapshot.setEffictivePrincipal(new BigDecimal("0"));
        loanSnapshot.setProductId("");
        loanSnapshot.setProductType("");
        loanSnapshot.setProductName("");
        loanSnapshot.setPurpose("");
        loanSnapshot.setInterestRate(new BigDecimal("0"));
        loanSnapshot.setOverdueInterestRate(new BigDecimal("0"));
        loanSnapshot.setPlatformServiceFeeRate(new BigDecimal("0"));
        loanSnapshot.setOverduePlatformServiceFeeRate(new BigDecimal("0"));
        loanSnapshot.setPremiumFeeRate(new BigDecimal("0"));
        loanSnapshot.setInstallments(0);
        loanSnapshot.setUnpaidInstallments(0);
        loanSnapshot.setDays(0);
        loanSnapshot.setDueAt(new Date());
        loanSnapshot.setPrincipal(new BigDecimal("0"));
        loanSnapshot.setInterest(new BigDecimal("0"));
        loanSnapshot.setOverdueInterest(new BigDecimal("0"));
        loanSnapshot.setPlatformServiceFee(new BigDecimal("0"));
        loanSnapshot.setOverduePlatformServiceFee(new BigDecimal("0"));
        loanSnapshot.setInstallmentPremiumFee(new BigDecimal("0"));
        loanSnapshot.setRepaymentFee(new BigDecimal("0"));
        loanSnapshot.setDueAmount(new BigDecimal("0"));
        loanSnapshot.setUnpaidPrincipal(new BigDecimal("0"));
        loanSnapshot.setUnpaidInterest(new BigDecimal("0"));
        loanSnapshot.setUnpaidOverdueInterest(new BigDecimal("0"));
        loanSnapshot.setUnpaidPlatformServiceFee(new BigDecimal("0"));
        loanSnapshot.setUnpaidOverduePlatformServiceFee(new BigDecimal("0"));
        loanSnapshot.setUnpaidInstallmentPremiumFee(new BigDecimal("0"));
        loanSnapshot.setUnpaidRepaymentFee(new BigDecimal("0"));
        loanSnapshot.setUnpaidDueAmount(new BigDecimal("0"));
        loanSnapshot.setRepaidPrincipal(new BigDecimal("0"));
        loanSnapshot.setRepaidInterest(new BigDecimal("0"));
        loanSnapshot.setRepaidOverdueInterest(new BigDecimal("0"));
        loanSnapshot.setRepaidPlatformServiceFee(new BigDecimal("0"));
        loanSnapshot.setRepaidOverduePlatformServiceFee(new BigDecimal("0"));
        loanSnapshot.setRepaidInstallmentPremiumFee(new BigDecimal("0"));
        loanSnapshot.setRepaidRepaymentFee(new BigDecimal("0"));
        loanSnapshot.setRepaidDueAmount(new BigDecimal("0"));
        loanSnapshot.setCurrency("");
        loanSnapshot.setCreatedAt(new Date());
        loanSnapshot.setUpdatedAt(new Date());
        loanSnapshot.setRepaidAt(new Date());
        loanSnapshot.setDerateFee(new BigDecimal("0"));
        loanSnapshot.setEffectiveAt(new Date());
        loanSnapshot.setFundedAt(new Date());
        loanSnapshot.setScenario("");
        loanSnapshot.setOneTimePenaltyRate(new BigDecimal("0"));
        loanSnapshot.setOneTimePenalty(new BigDecimal("0"));
        loanSnapshot.setUnpaidOneTimePenalty(new BigDecimal("0"));
        loanSnapshot.setRepaidOneTimePenalty(new BigDecimal("0"));
        loanSnapshot.setAmountLoss(new BigDecimal("0"));
        loanSnapshot.setGraceDay(0);
        loanSnapshot.setCalculator("");
        loanSnapshot.setLoanType("");
        loanSnapshot.setLoanScenario("");
        loanSnapshot.setEarlyRepaymentFee(new BigDecimal("0"));
        loanSnapshot.setUnpaidEarlyRepaymentFee(new BigDecimal("0"));
        loanSnapshot.setRepaidEarlyRepaymentFee(new BigDecimal("0"));
        loanSnapshot.setEarlyRepaymentServiceFee(new BigDecimal("0"));
        loanSnapshot.setUnpaidEarlyRepaymentServiceFee(new BigDecimal("0"));
        loanSnapshot.setRepaidEarlyRepaymentServiceFee(new BigDecimal("0"));
        loanSnapshot.setIsNPL(0);
        loanSnapshot.setIsEarlyPay(0);
        loanSnapshot.setSubsidy(new BigDecimal("0"));
        loanSnapshot.setEwt(new BigDecimal("0"));
        loanSnapshot.setSoldStatus(0);
        loanSnapshot.setAutoDeduct(0);
        loanSnapshot.setInsurancePremiumRate(new BigDecimal("0"));
        loanSnapshot.setInsurancePremiumFee(new BigDecimal("0"));
        loanSnapshot.setInsuranceCommissionRate(new BigDecimal("0"));
        loanSnapshot.setInsuranceCommissionFee(new BigDecimal("0"));
        loanSnapshot.setOriginDueAt(new Date());
        loanSnapshot.setHolidayDerateFee(new BigDecimal("0"));
        loanSnapshot.setPolicyGenerationFee(new BigDecimal("0"));
        loanSnapshot.setInsuranceCheckbox(0);
        loanSnapshot.setPolicyGenerationCheckbox(0);


        LoanEntity uptLoanEntity = BeanMapUtils.map(loanSnapshot, LoanEntity.class);
        System.out.println(uptLoanEntity);
    }
}
